# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_column_column_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_img',
            field=models.ImageField(default='pic_folder/None/no_image.pig', upload_to='article_img'),
        ),
    ]
